import { useEffect, useState } from 'react';
import { ChevronRight, GitMerge, GitPullRequest, CheckCircle2 } from 'lucide-react';
import Input from '../components/ui/Input';
import Badge from '../components/ui/Badge';
import { issuesService } from '../services/issuesService';
import type { Issue } from '../types';

const statusConfig: Record<string, { badge: 'success' | 'purple' | 'default'; icon: typeof GitPullRequest }> = {
  open: { badge: 'success', icon: GitPullRequest },
  merged: { badge: 'purple', icon: GitMerge },
  closed: { badge: 'default', icon: GitPullRequest },
};

export default function PullRequestsPage() {
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [issues, setIssues] = useState<Issue[]>([]);

  useEffect(() => {
    void issuesService.getAll().then(setIssues).catch(() => setIssues([]));
  }, []);

  const filtered = issues.filter((issue) => {
    const matchesSearch =
      issue.title.toLowerCase().includes(search.toLowerCase()) ||
      `#${issue.id}`.includes(search);
    const matchesStatus = statusFilter === 'all' || issue.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-[28px] font-semibold text-[#F8FAFC]">Pull Requests</h1>
        <p className="text-[14px] text-[#94A3B8] mt-1">
          Review pull requests generated by SWEPilot.
        </p>
      </div>

      {/* Controls */}
      <div className="flex flex-col sm:flex-row gap-3">
        <div className="flex-1 max-w-md">
          <Input
            icon
            placeholder="Search pull requests..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <div className="flex gap-2">
          {['all', 'open', 'merged', 'closed'].map((status) => (
            <button
              key={status}
              onClick={() => setStatusFilter(status)}
              className={`px-3 py-1.5 text-[13px] font-medium rounded-lg border transition-colors ${
                statusFilter === status
                  ? 'bg-[#3B82F6]/10 text-[#3B82F6] border-[#3B82F6]/30'
                  : 'bg-[#0D121C] text-[#94A3B8] border-[#1E293B] hover:bg-[#161D2A]'
              }`}
            >
              {status.charAt(0).toUpperCase() + status.slice(1)}
            </button>
          ))}
        </div>
      </div>

      {/* PR list */}
      <div className="bg-[#10151F] border border-[#1E293B] rounded-lg overflow-hidden">
        {filtered.map((issue, index) => {
          const config = statusConfig[issue.status] ?? statusConfig.open!;
          const StatusIcon = config.icon;

          return (
            <a
              key={issue.id}
              href={issue.pullRequestUrl ?? `https://github.com/${issue.repository}/pull/${issue.id}`}
              target="_blank"
              rel="noreferrer"
              className={`flex items-center gap-4 px-4 lg:px-5 py-4 hover:bg-[#161D2A] transition-colors ${
                index !== filtered.length - 1 ? 'border-b border-[#1E293B]' : ''
              }`}
            >
              <StatusIcon
                className={`w-5 h-5 flex-shrink-0 ${
                  issue.status === 'open'
                    ? 'text-[#22C55E]'
                    : issue.status === 'closed'
                      ? 'text-[#8B5CF6]'
                      : 'text-[#64748B]'
                }`}
              />

              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 flex-wrap">
                  <span className="text-[12px] font-mono text-[#64748B]">
                    Issue #{issue.id}
                  </span>
                  <span className="text-[14px] font-medium text-[#F8FAFC] truncate">
                    {issue.title}
                  </span>
                  <Badge variant={config.badge} size="sm">
                    {issue.status.replace('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())}
                  </Badge>
                </div>
                <div className="flex items-center gap-3 mt-1 text-[12px] text-[#64748B]">
                  <span>{issue.repository}</span>
                  <span className="flex items-center gap-1">
                    <CheckCircle2 className="w-3 h-3 text-[#22C55E]" />
                    {issue.agentStatus ?? 'pending'}
                  </span>
                  <span className="hidden sm:inline">{issue.createdAt}</span>
                </div>
              </div>

              <ChevronRight className="w-4 h-4 text-[#64748B] flex-shrink-0" />
            </a>
          );
        })}

        {filtered.length === 0 && (
          <div className="py-12 text-center text-[14px] text-[#64748B]">
            No pull requests found matching your criteria.
          </div>
        )}
      </div>
    </div>
  );
}
